version: '3.1'

volumes:
  node_modules:

services:
  node:
    build:
      context: .
    command: /bin/sh -c "node --inspect=0.0.0.0:8229 index.js"
    # command: /bin/sh -c "node --inspect=0.0.0.0:8229 dist/server.webpacked.js"
    ports:
      - "3000:3000"
      - "8229:8229"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development