version: '3.1'

services:
  node:
    build:
      context: .
    command: /bin/sh -c "BABEL_ENV=node node -r babel-register --inspect=0.0.0.0:8229 src/server"
    # command: /bin/sh -c "node --inspect=0.0.0.0:8229 dist/server.webpacked.js"
    ports:
      - "3000:3000"
      - "8229:8229"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development